server {
    listen 80;
    listen [::]:80;

    server_name
        yangmingzhe.com
        www.yangmingzhe.com
        skytakeout.yangmingzhe.com
        jobtracker.yangmingzhe.com;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name yangmingzhe.com www.yangmingzhe.com;

    ssl_certificate /etc/letsencrypt/live/yangmingzhe.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/yangmingzhe.com/privkey.pem;

    location / {
        proxy_pass http://127.0.0.1:8081;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name skytakeout.yangmingzhe.com;

    ssl_certificate /etc/letsencrypt/live/skytakeout.yangmingzhe.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/skytakeout.yangmingzhe.com/privkey.pem;

    client_max_body_size 20m;

    location / {
        proxy_pass http://127.0.0.1:8082;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 3600s;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name jobtracker.yangmingzhe.com;

    ssl_certificate /etc/letsencrypt/live/jobtracker.yangmingzhe.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/jobtracker.yangmingzhe.com/privkey.pem;

    location / {
        proxy_pass http://127.0.0.1:8083;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}