name: Portfolio CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download source code
        uses: actions/checkout@v7

      - name: Build Docker image
        run: docker build -t portfolio-site:ci .
